Repository rt-net/raspimouse_sim, pull requests merged in 2020-02, with the labels that each got.

#32 Add an index to each wall model name for fixing #26
  raspimouse_gazebo/worlds/sample_maze.world
Labels: bug

#31 パッケージの説明を更新
  README.ja.md
  README.md
Labels: documentation, in progress

#35 fix raspimouse_with_empetyworld.launch to load robot descrption
  raspimouse_gazebo/launch/raspimouse_with_emptyworld.launch
Labels: bug

#34 Add use_devfile argumet to launch files to make virtual device file optional
  raspimouse_control/launch/raspimouse_control.launch
  raspimouse_gazebo/launch/raspimouse_with_emptyworld.launch
  raspimouse_gazebo/launch/raspimouse_with_gasstand.launch
  raspimouse_gazebo/launch/raspimouse_with_samplemaze.launch
Labels: enhancement, in progress
